version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password_123"
      MYSQL_DATABASE: "SalesDB"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password_123"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: # <-- A CORREÇÃO ESTÁ AQUI
      - "5672:5672"   # Porta para a aplicação se conectar
      - "15672:15672"  # Porta para a interface web de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  mysql_data: